export type CardItem = {
  title: string;
  description: string;
  image: string;
  items: string[];
  badge?: string;
  term?: string;
  symptoms?: string[];
  href?: string;
};

export const commonProblems: CardItem[] = [
  { title: "Tooth Decay", term: "Dental Caries", image: "/images/pending/common-problems/02-tooth-decay.png", symptoms: ["Toothache", "Sensitivity to hot and cold foods", "Visible holes in teeth", "Pain while chewing"], description: "Dental fillings, fluoride treatment, crowns, or root canal treatment depending on severity.", href: "/treatments/dental-fillings", items: [] },
  { title: "Bleeding Gums", term: "Gingivitis", image: "/images/pending/common-problems/03-bleeding-gums.png", symptoms: ["Bleeding while brushing", "Swollen gums", "Bad breath", "Tender gum tissue"], description: "Professional scaling, improved oral hygiene, medicated mouthwash, and periodontal care.", href: "/treatments/teeth-cleaning-scaling", items: [] },
  { title: "Chronic Bad Breath", term: "Halitosis", image: "/images/pending/common-problems/04-chronic-bad-breath.png", symptoms: ["Persistent bad breath", "Dry mouth", "Unpleasant taste", "White coating on tongue"], description: "Professional cleaning, treatment of underlying dental issues, and improved oral hygiene habits.", href: "/treatments/general-dental-procedures", items: [] },
  { title: "Tooth Sensitivity", term: "Dentin Hypersensitivity", image: "/images/pending/common-problems/05-tooth-sensitivity.png", symptoms: ["Sharp pain with cold drinks", "Discomfort while eating sweets", "Sensitivity to hot foods", "Pain during brushing"], description: "Desensitizing toothpaste, fluoride therapy, bonding procedures, or gum treatment.", href: "/treatments/general-restorative", items: [] },
  { title: "Severe Tooth Infection", term: "Dental Abscess", image: "/images/pending/common-problems/06-severe-tooth-infection.png", symptoms: ["Persistent toothache", "Swelling around tooth", "Pus discharge", "Pain while biting"], description: "Root canal treatment, drainage of infection, antibiotics, or tooth extraction if necessary.", href: "/treatments/root-canal-treatment", items: [] },
  { title: "Crooked or Misaligned Teeth", term: "Malocclusion", image: "/images/pending/common-problems/07-crooked-or-misaligned-teeth.png", symptoms: ["Crowded teeth", "Difficulty cleaning teeth", "Bite problems", "Jaw discomfort"], description: "Clear aligners, braces, retainers, or orthodontic correction.", href: "/treatments/clear-aligners", items: [] },
  { title: "Wisdom Tooth Pain", term: "Impacted Third Molar", image: "/images/pending/common-problems/08-wisdom-tooth-pain.png", symptoms: ["Jaw pain", "Swollen gums", "Difficulty opening mouth", "Pain at back of mouth"], description: "Monitoring, medication, or surgical wisdom tooth extraction.", href: "/treatments/tooth-removal", items: [] },
  { title: "Teeth Grinding", term: "Bruxism", image: "/images/pending/common-problems/09-teeth-grinding.png", symptoms: ["Worn teeth", "Jaw pain", "Morning headaches", "Tooth sensitivity"], description: "Night guards, bite correction, stress management, and restorative dentistry.", href: "/treatments/dental-splints", items: [] },
  { title: "Missing Teeth", term: "Partial Edentulism", image: "/images/pending/common-problems/10-missing-teeth.png", symptoms: ["Difficulty chewing", "Speech issues", "Shifting of nearby teeth", "Bone loss in jaw"], description: "Dental implants, bridges, dentures, or full mouth rehabilitation.", href: "/treatments/dental-implants", items: [] },
  { title: "Yellow or Stained Teeth", term: "Extrinsic / Intrinsic Tooth Staining", image: "/images/pending/common-problems/11-yellow-or-stained-teeth.png", symptoms: ["Tooth discoloration", "Surface stains", "Uneven tooth shade", "Loss of smile confidence"], description: "Professional teeth whitening, bleaching, polishing, veneers, or smile makeover treatments.", href: "/treatments/cosmetic-dentistry", items: [] },
];

export const commonProblemFaqs = [
  ["When should I see a dentist for tooth pain?", "You should visit a dentist if tooth pain lasts more than a day or two, becomes severe, causes swelling, or interferes with eating and sleeping. Early diagnosis can prevent more complex treatments later."],
  ["Can bleeding gums be a sign of a serious dental problem?", "Yes. Bleeding gums are often an early sign of gingivitis or gum disease. If left untreated, gum disease can progress and affect the supporting structures of your teeth."],
  ["Why are my teeth sensitive to hot and cold foods?", "Tooth sensitivity may occur due to worn enamel, exposed tooth roots, cavities, gum recession, or teeth grinding. A dental examination can identify the exact cause and appropriate treatment."],
  ["What causes chronic bad breath?", "Persistent bad breath can result from poor oral hygiene, gum disease, tooth decay, dry mouth, or certain medical conditions. Professional cleaning and proper oral care often help resolve the issue."],
  ["Can crooked teeth affect oral health?", "Yes. Misaligned teeth can make brushing and flossing difficult, increasing the risk of cavities and gum disease. They may also contribute to bite problems and jaw discomfort."],
  ["When is a root canal treatment necessary?", "A root canal is usually recommended when the tooth pulp becomes infected or inflamed due to deep decay, trauma, or severe infection. The procedure helps save the natural tooth."],
  ["What are the treatment options for missing teeth?", "Common solutions include dental implants, bridges, dentures, and full mouth rehabilitation. The best option depends on your oral health, bone condition, and treatment goals."],
  ["Do wisdom teeth always need to be removed?", "Not always. Wisdom teeth only require removal when they are impacted, causing pain, infection, crowding, or damage to adjacent teeth."],
  ["Can yellow or stained teeth become white again?", "Yes. Professional teeth whitening, polishing, bleaching, veneers, and cosmetic dental treatments can significantly improve tooth color and appearance."],
  ["How can I prevent common dental problems?", "Maintaining good oral hygiene, brushing twice daily, flossing regularly, limiting sugary foods, and scheduling routine dental check-ups can help prevent most dental problems."],
] as const;

export const safetyGroups = [
  { eyebrow: "Patient-First Approach", title: "Comfortable care designed around you.", intro: "From personalized treatment plans to a welcoming environment, we ensure every patient feels heard, supported, and confident throughout their dental journey.", cards: [
    ["Comfort-First Experience", "Every treatment is planned with patient comfort in mind, creating a calm and stress-free dental experience from consultation to recovery."],
    ["Transparent Treatment Planning", "We explain diagnoses, treatment options, costs, and expected outcomes clearly, empowering patients to make informed decisions."],
    ["Gentle & Compassionate Care", "Our team prioritizes empathy, patience, and personalized attention to ensure every patient feels heard, valued, and comfortable."],
    ["Family-Friendly Environment", "From children to senior citizens, our clinic is designed to provide safe, welcoming, and accessible dental care for all age groups."],
  ] },
  { eyebrow: "Advanced Sterilization", title: "Safety and hygiene without compromise.", intro: "Our rigorous sterilization protocols and infection-control standards ensure a clean, safe, and worry-free experience for every patient.", cards: [
    ["Medical-Grade Instrument Sterilization", "All reusable instruments undergo thorough cleaning, packaging, and autoclave sterilization to eliminate bacteria, viruses, and contaminants."],
    ["Single-Use Disposable Materials", "Wherever applicable, disposable items are used once and safely discarded to maintain the highest standards of hygiene."],
    ["Operatory Disinfection Protocols", "Treatment areas are disinfected after every patient using approved medical-grade surface disinfectants and strict sanitation procedures."],
    ["Continuous Infection Control", "Our team maintains strict infection-control standards, with comprehensive hygiene practices, appropriate PPE usage, and routine safety checks to ensure a clean and safe environment for every patient."],
  ] },
  { eyebrow: "Modern Dental Technology", title: "Precision dentistry powered by innovation.", intro: "We utilize cutting-edge diagnostic tools and advanced treatment technologies to deliver accurate, efficient, and predictable dental care.", cards: [
    ["Digital Robotic Scanning", "High-precision digital scans replace traditional impressions, delivering greater comfort, accuracy, and treatment predictability."],
    ["3D Diagnostic Imaging", "Advanced imaging technology provides detailed visualization of teeth, bone, and surrounding structures for precise treatment planning."],
    ["Laser-Assisted Dentistry", "Modern dental lasers enable minimally invasive procedures with improved precision, reduced discomfort, and faster healing."],
    ["Technology-Driven Treatment Planning", "Digital workflows, AI-assisted diagnostics, and advanced planning tools help deliver predictable, efficient, and personalized care."],
  ] },
] as const;

export const postTreatmentCards: CardItem[] = [
  { title: "Root Canal Treatment (RCT)", image: "/images/pending/post-instruction/61-root-canal-treatment-rct.jpg", description: "Essential post-care guidelines to ensure successful recovery and longevity of your root canal therapy.", items: ["Avoid chewing or biting down on the treated tooth until it has been fully restored with a permanent crown.", "Mild tenderness or sensitivity is normal for a few days; take prescribed pain relievers as directed.", "Maintain your routine brushing and flossing, but clean around the temporary filling extra gently.", "Do not consume hard, crunchy, or extremely sticky foods on the side of the treated tooth.", "Contact the clinic immediately if your temporary filling falls out, or if swelling develops."] },
  { title: "Dental Implants", image: "/images/pending/post-instruction/62-dental-implants.png", description: "Critical healing instructions to support proper osseointegration and protect your surgical site.", items: ["Bite firmly on the gauze pack for 30–60 minutes following the surgery; slight oozing/bleeding is normal.", "Apply an ice pack externally (20 minutes on, 20 minutes off) for the first 24 hours to reduce swelling.", "Stick to a soft, room-temperature diet and avoid chewing directly on the implant site for the first few days.", "Take all prescribed antibiotics and anti-inflammatory medications precisely as instructed.", "Strictly avoid smoking, tobacco use, and alcohol consumption for at least 7–10 days to ensure proper bone healing."] },
  { title: "Crowns, Inlays & Onlays", image: "/images/pending/post-instruction/63-crowns-inlays-and-onlays.png", description: "Care protocols to ensure your dental caps remain strongly bonded and structurally sound.", items: ["Avoid eating or drinking hot liquids until the local anesthesia numbness has completely worn off.", "Do not chew hard, sticky, or crunchy foods for the first 24 hours to allow the bonding cement to mature.", "Mild temperature sensitivity is normal for a few days; use a sensitive-teeth toothpaste if necessary.", "Brush and floss daily; when flossing, pull the floss out sideways rather than snapping it upward.", "Contact the clinic if the restoration feels high when biting, feels loose, or detaches completely."] },
  { title: "Dental Veneers", image: "/images/pending/post-instruction/64-dental-veneers.png", description: "Helpful protection habits to keep your cosmetic veneers flawless, chip-free, and bright.", items: ["Avoid biting directly into hard foods (like apples, raw carrots, or tough bread) with your front teeth for 24–48 hours.", "Brush gently with a soft-bristled toothbrush and use non-abrasive toothpaste; floss daily.", "Eliminate habits such as nail-biting, chewing ice, holding pins, or opening packets with your teeth.", "Wear your prescribed night guard consistently if you have a tendency to grind or clench your teeth.", "Contact the clinic immediately if a veneer chips, loosens, or if your bite feels uneven."] },
  { title: "Dental Fillings", image: "/images/pending/post-instruction/65-dental-fillings.jpg", description: "Simple adjustments to follow after receiving a composite or silver filling.", items: ["If local anesthesia was used, do not chew or eat until your lips and tongue are fully awake.", "Avoid excessively hot, cold, or highly sugary foods and drinks if you experience mild post-op sensitivity.", "Skip hard foods, crunchy nuts, or sticky candies for the first 24 hours to protect the filling margins.", "Brush and floss regularly as instructed; fillings require excellent home care to prevent recurring decay.", "Notify the clinic if your bite feels uneven or high after the numbness wears off completely."] },
  { title: "Clear Aligners", image: "/images/pending/post-instruction/66-clear-aligners.jpg", description: "Daily discipline rules to keep your orthodontic aligner trajectory on schedule.", items: ["Wear your aligners for 20 to 22 hours every single day, removing them only to eat, drink, brush, and floss.", "Always brush your teeth and clean your aligners before putting them back into your mouth.", "Never drink hot liquids, sugary beverages, or colored drinks while wearing your aligner trays.", "Store your aligners inside their protective case whenever they are not inside your mouth to avoid loss or damage.", "Transition to your next set of trays exactly on the day prescribed by your orthodontist."] },
  { title: "Orthodontic Braces", image: "/images/pending/post-instruction/67-orthodontic-braces.jpg", description: "Essential dynamic care guidelines for managing traditional bracket and wire hardware.", items: ["Avoid hard foods (nuts, hard crusts) and sticky items (gum, caramel) that can snap brackets or bend wires.", "Use specialized orthodontic brushes and interdental cleaners to scrub thoroughly around brackets after every meal.", "Apply small pieces of orthodontic relief wax over any sharp brackets or poking wires that irritate your cheeks.", "Wear your elastic rubber bands or appliances exactly as directed by your orthodontist.", "Once braces are removed, wear your retainers strictly according to the prescribed timeline to prevent teeth shifting."] },
  { title: "Dental Bridges", image: "/images/pending/post-instruction/68-dental-bridges.jpg", description: "Specific oral hygiene maintenance protocols for cleaning fixed multi-unit prosthetics.", items: ["Avoid chewing hard, sticky, or crunchy foods for the first 24 hours while the permanent cement cures.", "Clean thoroughly under the artificial suspended tooth (pontic) daily using a floss threader or super floss.", "Brush carefully along the gum lines of the anchoring teeth to prevent plaque accumulation and decay.", "Avoid biting down on ice cubes or very hard candies that could fracture the porcelain structure.", "Schedule routine 6-month clinical visits so the integrity of the bridge margins can be closely monitored."] },
  { title: "Tooth Jewellery", image: "/images/pending/post-instruction/69-tooth-jewellery.jpg", description: "Aftercare instructions to keep your temporary tooth gem securely bonded and sparkling.", items: ["Avoid touching, moving, or playing with the tooth jewellery using your fingers or tongue for the first 24 hours.", "Stick to soft items and avoid hard, sticky, or chewy foods for the first 24–48 hours after application.", "Brush gently around the cosmetic jewellery with a soft-bristled toothbrush to maintain bright enamel.", "Do not attempt to pull off, pick at, scratch, or adjust the jewelry piece yourself at home.", "Contact the clinic immediately if the dental jewellery becomes loose, shifts, or falls off unexpectedly."] },
  { title: "Laser Procedures", image: "/images/pending/post-instruction/70-laser-procedures.jpg", description: "Soft tissue restoration guidelines to encourage rapid, smooth healing of laser surgical sites.", items: ["Eat soft, cool foods and strictly avoid hot, spicy, crunchy, and acidic foods for 24–48 hours.", "Do not pick at, scratch, or disturb the treated tissue with your fingers, toothpicks, or tongue.", "Brush teeth gently and rinse the area with the prescribed medicated mouthwash or a warm salt-water rinse.", "Avoid smoking, tobacco use, and alcohol consumption for at least 7–10 days to maximize tissue healing.", "Contact the clinic immediately if you notice unexpected, heavy, or excessive bleeding from the site."] },
  { title: "Tooth Extraction", image: "/images/pending/post-instruction/71-tooth-extraction.jpg", description: "Critical surgical rules to protect the extraction socket, promote blood clotting, and prevent dry socket.", items: ["Keep firm biting pressure on the surgical gauze pad for 30–60 minutes; spit it out gently after.", "Do NOT spit, smoke, use drinking straws, or rinse your mouth vigorously for the first 24 hours to protect the blood clot.", "Eat soft, cold foods (like yogurt, ice cream, or pudding) and avoid chewing on the extraction side.", "Avoid strenuous physical activities, heavy lifting, and workouts for 48 hours to minimize bleeding risks.", "Take your prescribed painkillers and antibiotics strictly as scheduled by your oral surgeon."] },
  { title: "Scaling & Polishing", image: "/images/pending/post-instruction/72-scaling-and-polishing.jpg", description: "Routine preventive maintenance care guidelines to preserve pristine, plaque-free oral health.", items: ["Expect mild gum sensitivity or light bleeding during brushing; this is normal and will clear up within 48 hours.", "Avoid highly pigmented foods and drinks (coffee, tea, red wine, turmeric) for 24 hours to keep the polished surface stain-free.", "Continue brushing twice daily with a soft-bristled brush, and make sure to incorporate daily flossing.", "Rinse with warm saltwater or a prescribed mouthwash if your gums feel tender or slightly raw.", "Schedule your next routine clinical cleaning in 6 months to maintain optimal periodontal wellness."] },
];

export const reviewCards = [
  ["Prateek Kumar", "16 May 2026", "Great service and painless treatment. Highly recommended if you are looking for the best dentist in Ghaziabad."],
  ["Jyoti Tyagi", "15 May 2026", "I had a great experience at Rekha Dental."],
  ["Poornima Gautam", "2 May 2026", "The doctors are highly experienced, and the treatment was smooth, painless, and very comfortable. I would definitely recommend Rekha Dental for quality dental care."],
  ["Sandeep Mandal", "30 Apr 2026", "Excellent work done by Dr. Gaurav and team. My RCT treatment was painless and I am very happy with the overall experience."],
  ["Amit Kumar", "14 Apr 2026", "Very nice experience. I am fully satisfied with the treatment."],
  ["Sweaty Mandal", "14 Apr 2026", "I recently got veneers done for my front tooth and I’m extremely happy with the results. The entire experience was smooth and comfortable."],
  ["Munni Yadav", "16 Feb 2026", "Professional and experienced doctors with great service and a very composed staff."],
  ["Azad Sirohi", "11 Feb 2026", "The treatment quality was outstanding and the staff made me feel extremely comfortable throughout the visit."],
  ["Samriddhi", "6 Feb 2026", "The doctors explained every treatment option clearly and ensured I was fully satisfied with the final result. A very reassuring experience."],
  ["Harshit Singh", "6 Feb 2026", "The clinic premises and behaviour of the doctors were excellent."],
] as const;

export const warrantyCards: CardItem[] = [
  { title: "Root Canal Treatment", badge: "6 Months", image: "/images/pending/warranty/73-root-canal-treatment.png", description: "Re-treatment may be considered within 6 months of the original treatment.", items: ["Valid if the treatment fails or the outcome is clinically unsatisfactory.", "Requires attendance at all scheduled follow-up appointments.", "Requires compliance with all post-treatment instructions.", "The tooth must not have been treated at another dental clinic.", "Excludes damage due to trauma, fracture, decay, or new infection.", "If a more advanced procedure is required, the cost difference may apply."] },
  { title: "Dental Implants", badge: "1–2 Years", image: "/images/pending/warranty/74-dental-implants.png", description: "Implant re-treatment may be considered within 1 year after completion of treatment.", items: ["All implant stages must be completed within the recommended timeline.", "Requires strict compliance with post-operative and oral hygiene instructions.", "Recommended Vitamin D and calcium levels must be maintained.", "Smoking and tobacco use must be avoided.", "Diabetic or hypertensive patients must attend all advised follow-up visits.", "Excludes treatment delays caused by the patient, trauma, or poor bone health.", "Additional procedures required during re-treatment may incur extra charges."] },
  { title: "Dental Crowns", badge: "1–2 Years", image: "/images/pending/warranty/75-dental-crowns.png", description: "Cementation-related issues may be considered under the re-treatment policy.", items: ["Covers crown debonding (cementation failure) within the warranty period.", "Patient must attend all recommended follow-up visits.", "The crown must not be modified or treated at another clinic.", "Excludes tooth pain, natural tooth fractures, or root canal failure beneath the crown.", "Excludes damage caused by trauma or accidental injury.", "Laboratory warranty applies only to eligible manufacturing defects."] },
  { title: "Dental Veneers", badge: "1 Year", image: "/images/pending/warranty/76-dental-veneers.png", description: "Treatment-related veneer issues may be considered within 6 months.", items: ["Covers veneer debonding due to cementation failure.", "Requires attendance at all follow-up appointments.", "Requires compliance with post-treatment instructions.", "No treatment must have been performed on the tooth elsewhere.", "Excludes damage from biting hard objects, trauma, accidental fractures, new decay, or gum disease."] },
  { title: "Dental Fillings", badge: "6 Months", image: "/images/pending/warranty/77-dental-fillings.png", description: "Filling replacement may be considered for treatment-related failure.", items: ["Covers fillings that become dislodged due to treatment-related causes.", "Patient must comply with all oral hygiene instructions.", "Recommended follow-up visits must be attended.", "Excludes new decay around the filling, tooth fractures, or damage from excessive biting forces and trauma."] },
  { title: "Clear Aligners", badge: "1 Year", image: "/images/pending/warranty/78-clear-aligners.png", description: "Covered under the orthodontic re-treatment policy.", items: ["Treatment must be completed exactly as prescribed.", "Aligners and retainers must be worn strictly as instructed.", "All scheduled appointments must be attended.", "Excludes cases where treatment is discontinued midway, retainers are neglected, or aligners are lost/damaged by the patient."] },
  { title: "Orthodontic Braces", badge: "1 Year", image: "/images/pending/warranty/79-orthodontic-braces.png", description: "Orthodontic re-treatment may be considered.", items: ["Treatment must be successfully completed, following all orthodontist instructions.", "Retainers must be worn consistently as prescribed.", "All scheduled appointments must be attended.", "Excludes issues arising from poor oral hygiene, failure to wear retainers, or missed appointments that impact the outcome."] },
  { title: "Dental Bridges", badge: "Case Based", image: "/images/pending/warranty/80-dental-bridges.png", description: "Bridge-related issues are evaluated clinically depending on the nature of the problem.", items: ["Manufacturing or cementation-related issues will be clinically evaluated.", "Patient must attend all scheduled follow-up appointments.", "Excludes natural tooth fractures, root canal failure of supporting teeth, or damage from trauma and accidents."] },
  { title: "Dentures", badge: "Case Based", image: "/images/pending/warranty/81-dentures.png", description: "Adjustments for comfort may be provided after delivery as advised by the dentist.", items: ["Dentures must be used strictly according to care and usage instructions.", "Patient must attend scheduled adjustment appointments.", "Excludes breakage from accidental dropping, loss of the denture, or changes in fit due to natural bone resorption over time."] },
  { title: "Dental Splints", badge: "Case Based", image: "/images/pending/warranty/82-dental-splints.png", description: "Manufacturing defects may be evaluated after clinical examination.", items: ["Splint must be used exactly according to instructions.", "Regular review appointments must be attended.", "Excludes loss, accidental damage, misuse, or chewing hard objects while wearing the splint."] },
  { title: "Immediate Implantology", badge: "1 Year", image: "/images/pending/warranty/83-immediate-implantology.png", description: "Covered under the Dental Implant re-treatment policy.", items: ["All implant treatment stages must be fully completed.", "Post-operative instructions and follow-up visits must be strictly adhered to.", "Excludes issues caused by smoking, tobacco use, poor oral hygiene, or patient-side delays in completing treatment."] },
  { title: "Tooth Jewellery", badge: "6 Months", image: "/images/pending/warranty/84-tooth-jewellery.png", description: "Bonding-related issues may be considered.", items: ["Covers instances where jewellery debonds due to bonding failure.", "Patient must follow all aftercare instructions.", "No external treatment must have been performed on the tooth.", "Excludes intentional removal, loss of the jewellery, or damage from trauma and biting hard foods."] },
];
